### ISSUE TITLE
Avoid the need to save generated javascript models in version control system

### ISSUE THREAD

**Issue by runephilosof-abtion** [kaspernj/api_maker#240]
It doesn't add a lot of value to have the generated javascript models in version control.
Also, it would be nice to not have to run `rails api_maker:generate_models` every time a resource is changed.

So, it would be a great improvement, if they could be generated dynamically in development/test.
Then for production, as part of the build, you could run the `api_maker:generate_models` task.

**Comment by kaspernj** [comment]
One of the concepts is actually to generate models to include in your code base. Not just for JavaScript but also for PHP, Java etc.

Kind of like what Apiomat is doing.

**Comment by kaspernj** [comment]
While it might be possible to do for Rails, it wouldn't be possible to not include it, if Rails wasn't bundled into it, which it probably wouldn't be in a Java project :-)

**Comment by runephilosof-abtion** [comment]
It would be cool for Rails projects. And for other use cases you could just run the task to have the files generated.
