### ISSUE TITLE
modelClassData.attributes should be an Object or Map

### ISSUE THREAD

**Issue by runephilosof-abtion** [kaspernj/api_maker#241]
The current Array of `attributes` is fine if you only need to iterate through them all.
But I would like to look up the `type` of one attribute.
Having the `attributes` as either an Object or Map would be good for both those use cases.

**Comment by kaspernj** [comment]
Which "attributes" specifically are you talking about? :-)
Can you link to an instance of it in the repo?

**Comment by runephilosof-abtion** [comment]
I am talkting about the attributes in javascript models returned by `modelClassData()`

**Comment by kaspernj** [comment]
Is this causing some sort of issue? Couldn't you just do a `.find` like this:
```js
`var roleAttribute = attributes.find(attribute => attribute.name == "role")
```
