### ISSUE TITLE
Returns error if value is array of hashes on nested_attributes

### ISSUE THREAD

**Issue by RobWu** [kaspernj/api_maker#272]
when saving array of hashes on nested_attributes (one-to-many) it returns error 
```
undefined method `keys' for #<Array:0x00007f9959d4f838>
.../api_maker-396c2714060c/app/services/api_maker/validation_errors_generator_service.rb:71:in `check_nested_many_models_for_validation_errors'
.../api_maker-396c2714060c/app/services/api_maker/validation_errors_generator_service.rb:55:in `block in inspect_params'
````
https://github.com/kaspernj/api_maker/blob/master/app/services/api_maker/validation_errors_generator_service.rb#L53-L55

**Comment by kaspernj** [comment]
@RobWu What is the case for this error? Can you write a spec for it maybe? :-)
